config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "users#index"
  resources :users, only: [:index, :show] do
    resources :recipes, only: [:index, :show, :new, :create, :destroy]
    resources :foods, only: [:index, :show, :new, :create, :destroy]
    resources :public_recipes, only: [:index]
    resources :shopping_list, only: [:index, :show]
  end

  resources :public_recipes, only: [:index]
  
  # Logout 
  get 'logout', to: 'sessions#destroy', as: 'logout'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :read, Recipe

    # Only owner of a recipe can delete it
    can :read, :all
    can :manage, Recipe, user_id: user.id

    # Show public recipe to owner also
    can :show, Recipe, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, foreign_key: :user_id

  validates :name, presence: true
  validates :quantity, presence: true
  validates :price, presence: true
  validates :measurement_unit, presence: true

  # Sum prices
  def self.total_price
    sum(:price)
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  attr_accessor :public

  before_save :set_public

  # Associations
  belongs_to :user, foreign_key: :user_id
  has_many :recipe_foods, dependent: :destroy

  # Validations
  validates :name, presence: true
  validates :description, presence: true
  validates :public, presence: true

  # Set public recipe attributes
  private

  def set_public
    self.public ||= false
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe, foreign_key: :recipe_id

  validates :quantity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { minimum: 2 }
  validates :password, presence: true
  validates :email, presence: true

  has_many :recipes, dependent: :destroy
  has_many :foods, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning

  # Set up user authentication
  before_action :authenticate_user!

  # Add addtional parameters
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Customize redirect hooks
  def after_sign_in_path_for(_resource)
    users_url
  end

  # Permit addtional parameters (@lazy)
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :sign_up, keys: %i[name email password confirm_password]
    )
    devise_parameter_sanitizer.permit(
      :sign_in, keys: %i[email password]
    )
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]

  # GET /foods or /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = Food.new(user_id: current_user.id, **food_params)

    respond_to do |format|
      if @food.save
        format.html do
          redirect_to user_food_url(current_user.id, @food.id), notice: 'food was successfully created.'
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    food = Food.find(params[:id])
    if food.destroy
      respond_to do |format|
        format.html { redirect_to user_foods_url, notice: 'Food was successfully destroyed.' }
      end
    else
      flash.now[:error] = 'Oops. Could not delete the food.'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @recipes = Recipe.where('public = ? OR user_id = ?', true, current_user.id).order('created_at DESC')
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1 or /recipes/1.json

  def show
    # Display foods in recipes
    @foods = Food.all
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(user_id: current_user.id, **recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html do
          redirect_to user_recipe_url(current_user.id, @recipe.id), notice: 'Recipe was successfully created.'
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    # @recipe.destroy
    recipe = Recipe.find(params[:id])
    if recipe.destroy
      respond_to do |format|
        format.html { redirect_to user_recipes_url, notice: 'Recipe was successfully destroyed.' }
      end
    else
      flash.now[:error] = 'Oops. Could not delete the post'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def destroy
    reset_session
    redirect_to root_path, notice: 'You have been logged out.'
  end
end

app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
  def index
    @foods = Food.where(user_id: current_user.id)
  end

  def show
    @foods = Food.where(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @foods = Food.where(user_id: current_user.id)
    @recipes = Recipe.where(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <p>
    <strong>Name:</strong>
    <%= food.name %>
  </p>

  <p>
    <strong>Measurement unit:</strong>
    <%= food.measurement_unit %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= food.price %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= food.quantity %>
  </p>

</div>

app/views/foods/_form.html.erb
<%= form_with model: food, url: user_foods_path do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :measurement_unit, style: "display: block" %>
    <%= form.text_field :measurement_unit %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.text_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/index.html.erb
<div class="show-foods-page">
  <h1>Foods</h1>

  <div class="add-food-btn">
    <%= link_to "Add food", new_user_food_path %>
  </div>
  <div class="foods">
    <% if @foods.empty? %>
      <p>No foods available.</p>
    <% else %>
      <table class="foods-table">
        <thead>
          <tr>
            <th>Food</th>
            <th>Measurement Unit</th>
            <th>Unit Price</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @foods.each do |food| %>
            <tr>
              <td class="food-names">
                <%= link_to food.name, user_food_url(current_user.id, food.id) %>
              </td>
              <td><%= food.measurement_unit %></td>
              <td><%= food.price %></td>
              <td>
                <%= button_to "Delete", 
                  user_food_path(current_user.id, food.id), method: :delete,
                  data: { confirm: "Delete food?" } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>

  <%= link_to "Go to Dashboard", users_path(current_user) %>
</div>

app/views/foods/new.html.erb
<div class="add-food-form">
  <h1>New food</h1>

  <%= render "form", food: @food %>

  <br>

  <div>
    <%= link_to "Back to foods", user_foods_path(current_user.id) %>
  </div>
</div>

app/views/foods/show.html.erb
<%= render @food %>
<div>
  <%= link_to "Back to foods", user_foods_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Food App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/public_recipes/_public_recipe_card.html.erb
<div class="public-recipe-card">
  <div class="public-recipe-card-head">
    <%= link_to user_recipe_path(current_user.id, recipe.id) do %>
      <h3><%= recipe.name %></h3>
    <% end %>
    <p>By: <%= recipe.user.name %></p>
  </div>

  <div>
    <p>Total food items: <%= %></p>
    <p>Total price: <%= %></p>
  </div>
</div>

app/views/public_recipes/index.html.erb
<div class="public-recipes">
  <h1>Public Recipes</h1>
  <div>
    <% if @recipes.empty? %>
      <p>No public recipes available.</p>
    <% else %>
      <% @recipes.each do |recipe| %>
        <%= render partial: 'public_recipe_card', locals: { recipe: recipe } %>
      <% end %>
    <% end %>
  </div>

  <p>
    <%= link_to "Back to Dashboard", users_path(current_user) %>
  </p>
</div>

app/views/recipes/_form.html.erb
<%= form_with model: recipe, url: user_recipes_path do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.text_field :preparation_time %>
  </div>

  <div>
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.text_field :cooking_time %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :Public %><br />
    <%= form.label :public, "Yes", value: "true"  %>
    <%= form.radio_button :public, true, checked: true %>
    <%= form.label :public, "No", value: "false" %>
    <%= form.radio_button :public, false %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <p>
    <strong>Name:</strong>
    <%= recipe.name %>
  </p>

  <p>
    <strong>Preparation time:</strong>
    <%= recipe.preparation_time %>
  </p>

  <p>
    <strong>Cooking time:</strong>
    <%= recipe.cooking_time %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= recipe.description %>
  </p>

  <p>
    <strong>Public:</strong>
    <%= recipe.public %>
  </p>

</div>

app/views/recipes/index.html.erb
<div class="user-recipes">
  <h1>Recipes</h1>

  <div class="recipes">
    <% if @recipes.empty? %>
      <p class="">No recipes available! </p>
    <% else %>
      <% @recipes.each do |recipe| %>
        <div class="user-recipe-info-card">
          <div class="recipe-name-remove">
            <h4>
              <%= link_to recipe.name, user_recipe_url(current_user.id, recipe.id) %>
            </h4>
            <% if can? :destroy, recipe %>
              <%= button_to "REMOVE", 
              user_recipe_path(current_user.id, recipe.id), method: :delete,
              data: { confirm: "Delete Recipe?" } %>
            <% end %>
          </div>
          <div>
            <p><%= recipe.description %></p>
          </div>
        </div>
      <% end %>
    <% end %>
    <div class="links">
      <%= link_to "New recipe", new_user_recipe_path(current_user) %>
      <%= link_to "Back to Dashboard", users_path(current_user) %>
    </div>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="add-recipe-form">
  <h1>New recipe</h1>

  <%= render "form", recipe: @recipe %>

  <br>

  <div>
    <%= link_to "Back to recipes", user_recipes_path(current_user) %>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="recipe-details">
  <h2><%= @recipe.name %></h2>
  <div class="recipe-info">
    <div class="recipe-info-field">
      <h4>Preparation time: </h4>
      <span><%= @recipe.preparation_time %> hours </span>
    </div>
    <div class="recipe-info-field">
      <h4>Cooking time: </h4>
      <span>
        <%= @recipe.cooking_time %> hours
      </span>
    </div>
    <div class="recipe-info-field">
      <h4>Steps are as follows: </br> </h4>
      <span>
        <%= @recipe.description %>
      </span>
    </div>
  </div>

  <div class="recipe-details-btns">
    <p>
      <%= link_to "Generate shopping list", user_shopping_list_path %>
    </p>
    <p>Add ingredient</p>
  </div>
  <hr/>
  <div>
  <table>
      <thead>
        <tr>
          <th>Food</th>
          <th>Quantity</th>
          <th>Value</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @foods.each do |food| %>
          <tr>
            <td>
              <%= food.name %>
            </td>
            <td><%= food.measurement_unit %></td>
            <td><%= food.price %></td>
            <td>
              <%= button_to "Remove", 
                user_food_path(current_user.id, food.id), method: :delete,
                data: { confirm: "Delete food?" } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="back-btn">
  <%= link_to "Back to recipes", user_recipes_path %>
</div>

app/views/shopping_list/index.html.erb
<div class="shopping-list">
  <p>This is the shopping list</p>
</div>

app/views/shopping_list/show.html.erb
<div class="shopping-cart">
  <h1>Shopping List</h1>

  <div>
    <% if @foods.empty? %>
      <p>No food items in the your shopping list</p>

      <div class="links">
        <%= link_to "Add Food", new_user_food_path(current_user) %>
        <%= link_to "Back to Dashboard", users_path(current_user) %>
      </p>
    <% else %>
    <div class="shopping-cart-head">
      <p>Ammount of food items to buy: <%= @foods.count() %></p>
      <p>Total value of food needed: <%= Food.total_price %></p>
    </div>
      <table>
        <thead>
          <tr>
            <th>Food</th>
            <th>Quantity</th>
            <th>Value</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @foods.each do |food| %>
            <tr>
              <td>
                <%= food.name %>
              </td>
              <td><%= food.measurement_unit %></td>
              <td><%= food.price %></td>
              <td>
                <%= button_to "Remove", 
                  user_food_path(current_user.id, food.id), method: :delete,
                  data: { confirm: "Delete food?" } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
    <p>
      <%= link_to "Back to Dashboard", users_path(current_user) %>
    </p>       
  </div>
</div>

app/views/users/index.html.erb
<div class="home-page">
  <div class="nav">
    <h3>Hello <%= current_user.name %>!</h3>
    <%= link_to "Logout", logout_path, method: :delete %>
  </div>
  <hr/>
  <div class="home-body">
    <div class="foods-home">
      <h3>Foods</h3>
      <% if @foods.empty? %>
        <p>No foods available.</p>
        <div>
          <p>
            <%= link_to "Add Food", new_user_food_path(current_user) %>
          </p>
        </div>
      <% else %>
        <p>Foods available:
          <span><%= @foods.count() %></span>
        </p>
        <p>
          <%= link_to "View Foods", user_foods_path(current_user) %>
        </p>
      <% end %>
    </div>

    <div class="recipes-home">
      <h3>Recipes</h3>
      <% if @recipes.count() < 1  %>
        <p>No recipes available</p>
        <div>
          <p>
            <%= link_to "Add Recipe", new_user_recipe_path(current_user) %>
          </p>
        </div>
      <% else %>
        <p>Recipes available:
          <span><%= @recipes.count() %></span>
        </p>
        <p>
          <%= link_to "View Recipes", user_recipes_path(current_user) %>
        </p>
      <% end %>
    </div>

    <div class="public-recipes-btn">
      <p>
        <%= link_to "View Public Recipes", user_public_recipes_path(current_user) %>
      </p>
    <div>
  </div>
</div>